<?php

namespace App\Imports;

use App\Models\User;
use Maatwebsite\Excel\Concerns\ToModel;

class UsersImport implements ToModel
{
    public function model(array $row)
    {
        return new User([
            'ma' => $row[0],
            'ma_so' => $row[1],
            'ma_chi_tiet' => $row[2],
            'tinh_trang' => $row[3],
            'ho_va_ten' => $row[4],
            'gioi_tinh' => $row[5],
            'nam_sinh' => $row[6],
            'ngay' => $row[7],
            'thang' => $row[8],
            'nam' => $row[9],
            'so_cmt' => $row[10],
            'ngay_cap' => $row[11],
            'noi_cap' => $row[12],
            'so_ho_chieu' => $row[13],
            'ngay_cap_1' => $row[14],
            'noi_cap_1' => $row[15],
            'dan_toc' => $row[16],
            'ton_giao' => $row[17],
            'quoc_tich' => $row[18],
            'trinh_do' => $row[19],
            'chuyen_mon' => $row[20],
            'noi_sinh' => $row[21],
            'nguyen_quan' => $row[22],
            'dia_chi_thuong_tru' => $row[23],
            'ngay_ket_nap_dang' => $row[24],
            'noi_ket_nap_dang' => $row[25],
            'dt_lien_he' => $row[26],
            'email' => $row[27],
            'mst_tncn' => $row[28],
            'so_tai_khoan_ca_nhan' => $row[29],
            'ngay_duoc_tuyen_dung' => $row[30],
            'td_theo_kh_hay_ps' => $row[31],
            'so_nguoi_yeu_cau_td' => $row[32],
            'so_nguoi_da_td' => $row[33],
            'thoi_gian_lam_viec_tai_hhp' => $row[34],
            'loai_lao_dong' => $row[35],
            'bo_phan' => $row[36],
            'chuc_vu' => $row[37],
            'chuc_vu_kiem_nhiem' => $row[38],
            'chuc_danh_chuyen_mon' => $row[39],
            'noi_lv' => $row[40],
            'he_so_luong' => $row[41],
            'muc_luong_thoa_thuan' => $row[42],
            'phu_cap_xang_xe' => $row[43],
            'pc_dien_thoai' => $row[44],
            'pc_trach_nhiem' => $row[45],
            'pc_khac' => $row[46],
            'tong_phu_cap' => $row[47],
            'tong_thu_nhap' => $row[48],
            'thoi_diem_huong' => $row[49],
            'so_hdld' => $row[50],
            'loai_hdld' => $row[51],
            'ngay_ky' => $row[52],
            'ngay_het_han' => $row[53],
            'da_dong_bh_hay_chua' => $row[54],
            'thang_dong_bh' => $row[55],
            'thoi_gian_dong_bh_tai_hhp' => $row[56],
            'so_so_bhxh' => $row[57],
            'so_the_bhyt' => $row[58],
            'ngach_luong_bhxh' => $row[59],
            'bac' => $row[60],
            'hs_luong' => $row[61],
            'hs_pc' => $row[62],
            'muc_luong_bhxh' => $row[63],
            'thoi_diem_huong_1' => $row[64],
            'thoi_gian_nang_bac_luong_gan_nhat' => $row[65],
            'thuoc_nhom_dieu_chinh_luong' => $row[66],
            'qua_trinh_cong_tac_truoc_khi_vao_hhp' => $row[67],
            'qua_trinh_cong_tac_tai_hhp' => $row[68],
            'mo_ta_cong_viec_chinh_hien_tai' => $row[69],
            'ten_khoa_dao_tao' => $row[70],
            'thoi_gian_dao_tao' => $row[71],
            'tu_ngay_thang' => $row[72],
            'den_ngay_thang' => $row[73],
            'chi_phi_dao_tao' => $row[74],
            'ket_qua_dao_tao' => $row[75],
            'cam_ket_dao_tao' => $row[76],
            'khen_thuong' => $row[77],
            'ky_luat' => $row[78],
            'ly_do_khen_thuong_ky_luat' => $row[79],
            'hinh_thuc_khen_thuong_ky_luat' => $row[80],
            'duoc_cap_bhld_hay_khong' => $row[81],
            'loai_bhld' => $row[82],
            'so_luong' => $row[83],
            'don_gia' => $row[84],
            'thanh_tien' => $row[85],
            'ngay_cap_2' => $row[86],
            'ngay_het_han_dinh_muc' => $row[87],
            'da_duoc_tap_huan_atvsld_hay_chua' => $row[88],
            'ngay_viet_don' => $row[89],
            'ngay_nghi_viec' => $row[90],
            'ly_do' => $row[91],
            'ttcd_so' => $row[92],
            'ngay_tra_so_bhxh' => $row[93],
            'anh' => $row[94],
            'ho_ten_bo_me' => $row[95],
            'nam_sinh_bo_me' => $row[96],
            'nghe_nghiep' => $row[97],
            'noi_o' => $row[98],
            'ho_ten_anh_chi_em_ruot' => $row[99],
            'nam_sinh_1' => $row[100],
            'nghe_nghiep_1' => $row[101],
            'noi_o_1' => $row[102],
            'vo_chong_con' => $row[103],
            'nam_sinh_2' => $row[104],
            'nghe_nghiep_2' => $row[105],
            'noi_o_2' => $row[106],
            'noi_o_hien_tai' => $row[107],
            'so_qd_cham_dut_hd' => $row[108],
        ]);
    }
}

